<?php
defined('_JEXEC') or die('Restricted access: It is not allowed to open this file directly!');

echo "<style> "
. "table.orderReport{ "
. "  color: #10253F; "
. "  max-width: 100%; "
. "  width: 100%; "
. "  background-color: #DDDDDD; "
. "  border-collapse: collapse; "
. "  border:thin solid #949494; "
. "  border-left:thin solid #949494; "
. "  border-right:thin solid #949494; "
. "  border-bottom:thin solid #949494; "
. "  empty-cells:show; "
. "  border-spacing:8px; "
. "  max-width: 97%; "
. "} "
. "td.orderReport{ "
. "  color: #10253F; "
. "  background-color: #DCE6F2; "
. "  border-collapse: collapse; "
. "  border:medium solid #A7B9D0; "
. "  empty-cells:show; "
. "  padding:1px; "
. "  font-size:85%; "
. "} "
. "th.orderReport{ "
. "  font-weight:bold; "
. "  color: #10253F; "
. "  background-color: #819EB1; "
. "  border-collapse: collapse; "
. "  border:medium solid #A7B9D0; "
. "  empty-cells:show; "
. "  padding:2px; "
. "  font-size:85%; "
. "} "
. "</style> ";
?>
